hl.on("hyprland.start", function ()
   hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
   hl.exec_cmd("waybar")
   hl.exec_cmd("sleep 1 && hyprpaper")
   hl.exec_cmd("pkill mako 2>/dev/null || true; swaync")
end)
